### ISSUE TITLE
Error report from pikachu01 at SHSForums

### ISSUE THREAD

**Issue by agb1** [K4thos/EET_Tweaks#1]
http://www.shsforums.net/topic/56670-big-world-setup-an-attempt-to-update-the-program/page-100#entry583474

Installing [Remove junk from global scripts] [beta 0.1]
Creating 1 directory
Copying 1 file ...
Compiling 3 scripts ...

[EET_Tweaks/28/K#LILARC.baf] PARSE ERROR at line 155 column 1-66
Near Text: )
    [RealSetGlobalTimer] argument [TWENTY_MINUTES] not found in [GTimes.IDS]

[EET_Tweaks/28/K#LILARC.baf] PARSE ERROR at line 159 column 1-66
Near Text: )
    [RealSetGlobalTimer] argument [TWENTY_MINUTES] not found in [GTimes.IDS]

[EET_Tweaks/28/K#LILARC.baf] PARSE ERROR at line 163 column 1-66
Near Text: )
    [RealSetGlobalTimer] argument [TWENTY_MINUTES] not found in [GTimes.IDS]

[EET_Tweaks/28/K#LILARC.baf] PARSE ERROR at line 167 column 1-66
Near Text: )
    [RealSetGlobalTimer] argument [TWENTY_MINUTES] not found in [GTimes.IDS]

[EET_Tweaks/28/K#LILARC.baf] PARSE ERROR at line 171 column 1-66
Near Text: )
    [RealSetGlobalTimer] argument [TWENTY_MINUTES] not found in [GTimes.IDS]

[EET_Tweaks/28/K#LILARC.baf] PARSE ERROR at line 175 column 1-66
Near Text: )
    [RealSetGlobalTimer] argument [TWENTY_MINUTES] not found in [GTimes.IDS]

[EET_Tweaks/28/K#LILARC.baf] PARSE ERROR at line 179 column 1-66
Near Text: )
    [RealSetGlobalTimer] argument [TWENTY_MINUTES] not found in [GTimes.IDS]

[EET_Tweaks/28/K#LILARC.baf] PARSE ERROR at line 183 column 1-66
Near Text: )
    [RealSetGlobalTimer] argument [TWENTY_MINUTES] not found in [GTimes.IDS]

[EET_Tweaks/28/K#LILARC.baf] PARSE ERROR at line 187 column 1-66
Near Text: )
    [RealSetGlobalTimer] argument [TWENTY_MINUTES] not found in [GTimes.IDS]

[EET_Tweaks/28/K#LILARC.baf] PARSE ERROR at line 191 column 1-66
Near Text: )
    [RealSetGlobalTimer] argument [TWENTY_MINUTES] not found in [GTimes.IDS]

[EET_Tweaks/28/K#LILARC.baf] PARSE ERROR at line 195 column 1-66
Near Text: )
    [RealSetGlobalTimer] argument [TWENTY_MINUTES] not found in [GTimes.IDS]

[EET_Tweaks/28/K#LILARC.baf] PARSE ERROR at line 199 column 1-66
Near Text: )
    [RealSetGlobalTimer] argument [TWENTY_MINUTES] not found in [GTimes.IDS]

[EET_Tweaks/28/K#LILARC.baf] PARSE ERROR at line 203 column 1-66
Near Text: )
    [RealSetGlobalTimer] argument [TWENTY_MINUTES] not found in [GTimes.IDS]

[EET_Tweaks/28/K#LILARC.baf] PARSE ERROR at line 207 column 1-66
Near Text: )
    [RealSetGlobalTimer] argument [TWENTY_MINUTES] not found in [GTimes.IDS]

[EET_Tweaks/28/K#LILARC.baf] PARSE ERROR at line 211 column 1-66
Near Text: )
    [RealSetGlobalTimer] argument [TWENTY_MINUTES] not found in [GTimes.IDS]

[EET_Tweaks/28/K#LILARC.baf] PARSE ERROR at line 215 column 1-66
Near Text: )
    [RealSetGlobalTimer] argument [TWENTY_MINUTES] not found in [GTimes.IDS]

[EET_Tweaks/28/K#LILARC.baf] PARSE ERROR at line 219 column 1-66
Near Text: )
    [RealSetGlobalTimer] argument [TWENTY_MINUTES] not found in [GTimes.IDS]

[EET_Tweaks/28/K#LILARC.baf] PARSE ERROR at line 223 column 1-66
Near Text: )
    [RealSetGlobalTimer] argument [TWENTY_MINUTES] not found in [GTimes.IDS]

[EET_Tweaks/28/K#LILARC.baf] PARSE ERROR at line 227 column 1-66
Near Text: )
    [RealSetGlobalTimer] argument [TWENTY_MINUTES] not found in [GTimes.IDS]

[EET_Tweaks/28/K#LILARC.baf] PARSE ERROR at line 231 column 1-66
Near Text: )
    [RealSetGlobalTimer] argument [TWENTY_MINUTES] not found in [GTimes.IDS]

[EET_Tweaks/28/K#LILARC.baf] PARSE ERROR at line 235 column 1-66
Near Text: )
    [RealSetGlobalTimer] argument [TWENTY_MINUTES] not found in [GTimes.IDS]
Copying and patching 2 files ...
WARNING: cannot find block matching [EET_Tweaks/28/Harpell.baf]

**Comment by K4thos** [comment]
thanks, fixed
