### ISSUE TITLE
BG2EE:  ERROR Installing [Protagonist can die]

### ISSUE THREAD

**Issue by agb1** [K4thos/EET_Tweaks#2]
[.../14/baldur-et.baf] PARSE ERROR at line 9 column 1-19
Near Text: )
	[GameOver] not found in ACTION.IDS

**Comment by K4thos** [comment]
thanks. Added this to fix it:
APPEND ~ACTION.IDS~ ~366 GameOver(I:StrRef*)~ UNLESS ~366 GameOver(I:StrRef*)~
