### ISSUE TITLE
Adjust XP for Quests & XP Awarded Individually encounter errors patching ALDETH.DLG

### ISSUE THREAD

**Issue by agb1** [K4thos/EET_Tweaks#4]
ALDETH.DLG was patched first by Item Randomiser, so not sure if this also occurs with original.

http://www.shsforums.net/topic/56670-big-world-setup-an-attempt-to-update-the-program/?p=586268

Logs attached to the post above.

**Comment by K4thos** [comment]
unrelated to EET Tweaks: http://www.shsforums.net/topic/56670-big-world-setup-an-attempt-to-update-the-program/page-140#entry586370
